#Welcome to our Lab practice!

This lab is all about the package, Numpy. Are you ready? Let's go!

You will find some small tasks in sections below. 

> Try to figure out by yourself, or search for references. Being able to search and find information needed is an important skill that benefits you and your career for a long time.

## Import the package and rename it as np

In [ ]:
import numpy as np

## Array Creation

### Task: Create a numpy array from a list of integers

In [ ]:
x = np.array([1, 2, 3, 4, 5])
x

### Task: Create a numpy array of size 6, filled with zeros

In [ ]:
x = np.zeros(6)
x

###Task: Create a numpy array of size 6, filled with ones

In [ ]:
x = np.ones(6)
x

###Task: Create a numpy array with values from 0 to 10

In [ ]:
x = np.arange(11)
x

###Task: Create a numpy matrix of 2*3 integers, filled with zeros

In [ ]:
X = np.zeros((2, 3))
X

###Task: Create a numpy matrix of 3*2 integers, filled with ones

In [ ]:
X = np.ones((3, 2))
X

###Task: Create a numpy matrix of 3*2 integers, filled with random integers in [0, 10]

In [ ]:
X = np.random.randint(0, 10, (3, 2))
X

###Task: Create a numpy matrix of 100 * 2, filled with random float value in [0, 1]

In [ ]:
X = np.random.random((100, 2))
X

###Task: Create a numpy matrix of 2\*3\*4, filled with integers from 1 to 24.

In [ ]:
X = np.arange(1, 25).reshape(2, 3, 4)
X

## Array Indexing

### Task: Let X be a numpy array, and X = np.array([1, 2, 3, 4, 5])

In [ ]:
X = np.array([1, 2, 3, 4, 5])

### Task: Show the first element of X

In [ ]:
X[0]

### Task: Show the last element of X

In [ ]:
X[-1]

### Task: Show the first 3 elements of X

In [ ]:
X[:3]

###Task: Show the last 3 elements of X

In [ ]:
X[2:]

###Task: Show the elements of X whose index is odd (1, 3, 5, ...)

In [ ]:
X[1::2]

###Task: Show the elements of X except the last one

In [ ]:
X[:-1]

### Task: Let X be a numpy matrix with dimension 3 * 4, and filled from 0 to 11.

In [ ]:
X = np.arange(12).reshape(3, 4)
X

###Task: Show the first row of X

In [ ]:
X[0]

###Task: Show the first column of X

In [ ]:
X[:,0]

###Task: Show the first element of the first row of X

In [ ]:
X[0,0]

###Task: Show the last row of X

In [ ]:
X[-1]

###Task: Show the last column of X

In [ ]:
X[:,-1]

###Task: Show the last element of the last row of X

In [ ]:
X[-1,-1]

###Task: Show all the rows except the last row of X

In [ ]:
X[:-1]

###Task: Show all the columns except the last column of X

In [ ]:
X[:,:-1]

### Task: Show the first two elements of the first two rows

In [ ]:
X[:2,:2]

## Array Statistics

###Task: Create a numpy array X, print the sum, mean, std, var, max, min of it

In [ ]:
print(X.sum(),X.mean(), X.std(), X.var(), X.max(), X.min())

###Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st row of it.

In [ ]:
r1 = X[0]
print(r1.sum(),r1.mean(), r1.std(), r1.var(), r1.max(), r1.min())

###Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st column of it.

In [ ]:
c1 = X[:,0]
print(c1.sum(),c1.mean(), c1.std(), c1.var(), c1.max(), c1.min())

## Array Linear Algebra

###Task: Create two numpy matrix X with 2 * 2, and Y with 2 * 2. Practice Linear Algebra operations, such as +, -, *, .T, @, etc.

In [ ]:
X = np.array([[0, 1], [2, 3]])
Y = np.array([[4, 5], [6, 7]])
plus = X + Y
minus = X - Y
times = X * Y
trans = X.T
prod = X @ Y
print(X)
print(Y)
print(plus)
print(minus)
print(times)
print(trans)
print(prod)